FaturaYönetimSistemi/Areas/Admin/Controllers/OdemeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OdemeSistemi.Application.OdemeOperation.Queries;

namespace FaturaYönetimSistemi.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OdemeController : Controller
    {
        string baseUrl = "https://localhost:7200";
        public async Task<IActionResult> GetOdemeler()
        {
            var httpClient = new HttpClient();
            var responseMessage = await httpClient.GetAsync(baseUrl + "/api/Odeme");
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            var odemeler = JsonConvert.DeserializeObject<List<GetOdemeViewModel>>(jsonString);
            return View(odemeler);
        }
    }
}

FaturaYönetimSistemi/Controllers/OdemeController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OdemeSistemi.Entities;
using System.Text;

namespace FaturaYönetimSistemi.Controllers
{
    public class OdemeController : Controller
    {
        KullanıcıManager kullanıcıManager = new(new EFKullanıcıRepository());
        FaturaManager faturaManager = new(new EFFaturaRepository());
        AidatManager aidatManager = new(new EFAidatRepository());
        string baseUrl = "https://localhost:7200/";

        [HttpGet]
        public IActionResult GetOdenmemisAidat()
        {
            var aidatlar = aidatManager.GetAllQueryWithKullanıcı()
                .Where(x => x.AidatOdendiMi == false && x.AidatKullanıcıId == kullanıcıManager.GetKullanıcıBySession(User.Identity.Name).KullanıcıId)
                .ToList<Aidat>();
            ViewBag.odenmemisAidatSayısı = aidatlar.Count();
            return View(aidatlar);
        }

        [HttpGet]
        public IActionResult GetOdenmemisFatura()
        {
            var faturalar = faturaManager.GetAllQueryWithKullanıcı()
                .Where(x => x.FaturaOdendiMi == false && x.FaturaKullanıcıId == kullanıcıManager.GetKullanıcıBySession(User.Identity.Name).KullanıcıId)
                .ToList<Fatura>();
            ViewBag.odenmemisFaturaSayısı = faturalar.Count();
            return View(faturalar);
        }

        [HttpGet]
        public IActionResult AidatOdeme(int id)
        {
            var aidat = aidatManager.GetQueryById(id);
            Odeme odeme = new Odeme();
            odeme.OdemeNetTutarı = aidat.AidatUcreti;
            odeme.OdemeAidatId = id;
            return View(odeme);
        }

        [HttpPost]
        public async Task<IActionResult> AidatOdeme(Odeme odeme)
        {
            var kullanıcı = kullanıcıManager.GetKullanıcıBySession(User.Identity.Name);

            odeme.OdemeTarihi = DateTime.Now;
            odeme.OdemeYapanKullanıcıEmail = kullanıcı.KullanıcıEmail;
            odeme.OdemeYapanKullanıcıId = kullanıcı.KullanıcıId;
            odeme.OdemeYapanKullanıcıIsim = kullanıcı.KullanıcıIsım;
            odeme.OdemeYapanKullanıcıSoyisim = kullanıcı.KullanıcıSoyisim;
            odeme.OdemeYapanKullanıcıTCNo = kullanıcı.KullanıcıTCNo;
            odeme.OdemeTutarı = odeme.OdemeNetTutarı;

            var httpClient = new HttpClient();
            var jsonOdeme = JsonConvert.SerializeObject(odeme);
            StringContent stringContent = new StringContent(jsonOdeme, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PostAsync(baseUrl + "api/Odeme", stringContent);

            if (responseMessage.IsSuccessStatusCode)
            {
                aidatManager.UpdateAidatDurumu(odeme.OdemeAidatId);
                return RedirectToAction("GetAidat","Aidat");
            }
            else
            {
                ViewBag.Message = "Ödeme gerçekleştirilirken bir hata oluştu, tekrar deneyiniz.";
            }
            return View();
        }

        [HttpGet]
        public IActionResult FaturaOdeme(int id)
        {
            var fatura = faturaManager.GetQueryById(id);
            Odeme odeme = new Odeme();
            odeme.OdemeNetTutarı = fatura.FaturaTutarı;
            odeme.OdemeFaturaId = id;
            odeme.OdemeFaturaTipi = fatura.FaturaTipi;
            return View(odeme);
        }

        [HttpPost]
        public async Task<IActionResult> FaturaOdeme(Odeme odeme)
        {
            var kullanıcı = kullanıcıManager.GetKullanıcıBySession(User.Identity.Name);

            odeme.OdemeTarihi = DateTime.Now;
            odeme.OdemeYapanKullanıcıEmail = kullanıcı.KullanıcıEmail;
            odeme.OdemeYapanKullanıcıId = kullanıcı.KullanıcıId;
            odeme.OdemeYapanKullanıcıIsim = kullanıcı.KullanıcıIsım;
            odeme.OdemeYapanKullanıcıSoyisim = kullanıcı.KullanıcıSoyisim;
            odeme.OdemeYapanKullanıcıTCNo = kullanıcı.KullanıcıTCNo;
            odeme.OdemeTutarı = odeme.OdemeNetTutarı;

            var httpClient = new HttpClient();
            var jsonOdeme = JsonConvert.SerializeObject(odeme);
            StringContent stringContent = new StringContent(jsonOdeme, Encoding.UTF8, "application/json");
            var responseMessage = await httpClient.PostAsync(baseUrl + "api/Odeme", stringContent);

            if (responseMessage.IsSuccessStatusCode)
            {
                faturaManager.UpdateFaturaById(odeme.OdemeFaturaId);
                return RedirectToAction("GetFatura","Fatura");
            }
            else
                ViewBag.Message = "Ödeme gerçekleştirilirken bir hata oluştu, tekrar deneyiniz.";
            return View();
        }
    }
}

FaturaYönetimSistemi/Views/Odeme/AddOdeme.cshtml
@using OdemeSistemi.Entities
@model Odeme
@{
    ViewData["Title"] = "AddOdeme";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!-- Top header -->
<header class="navbar-toggler p-4">
    <p class="w3-left text-dark font-weight-bolder" style="font-size:20px">Ödeme Sayfası</p>
    <p class="w3-right text-dark font-weight-normal" style="font-size:20px">
        <i class="icon-calendar mr-2"></i>@DateTime.Now.ToLongDateString()
    </p>
</header>
<hr />

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("AddOdeme", "Odeme", FormMethod.Post))
{
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarası, "Kart Numarası")
            @Html.TextBoxFor(model => model.OdemeKartNumarası, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeKartNumarası, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKrediKartıUzerindekiIsim, "Kart Üzerindeki İsim")
            @Html.TextBoxFor(model => model.OdemeKrediKartıUzerindekiIsim, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıUzerindekiIsim, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımAy, "Kart Son Kullanım Tarihi - Ay")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımAy, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımAy, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımYıl, "Kart Son Kullanım Tarihi- Yıl")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımYıl, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımYıl, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKrediKartıCVV, "CVV")
            @Html.TextBoxFor(model => model.OdemeKrediKartıCVV, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıCVV, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeTutarı, "Odeme Miktarı")
            @Html.TextBoxFor(model => model.OdemeTutarı, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeTutarı, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeYapanKullanıcıSehir, "Sehir")
            @Html.TextBoxFor(model => model.OdemeYapanKullanıcıSehir, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeYapanKullanıcıSehir, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeYapanKullanıcıUlke, "Ülke")
            @Html.TextBoxFor(model => model.OdemeYapanKullanıcıUlke, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OdemeYapanKullanıcıUlke, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <button class="btn btn-outline-primary" style="margin-left:0.75cm" onclick="return confirm('Ödeme gerçekleştiriliyor, onaylıyor musunu?')">
        Ödeme Yap
        <i class="icon-payment ml-2"></i>
    </button>
}

FaturaYönetimSistemi/Views/Odeme/AidatOdeme.cshtml
@using OdemeSistemi.Entities
@model Odeme
@{
    ViewData["Title"] = "AidatOdeme";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!-- Top header -->
<header class="navbar-toggler p-4">
    <p class="w3-left text-dark font-weight-bolder" style="font-size:20px">Aidat Ödeme Sayfası</p>
    <p class="w3-right text-dark font-weight-normal" style="font-size:20px">
        <i class="icon-calendar mr-2"></i>@DateTime.Now.ToLongDateString()
    </p>
</header>
<hr />

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("AidatOdeme", "Odeme", FormMethod.Post))
{
    <div class="d-flex flex-row col-md-12">
        @Html.HiddenFor(model => model.OdemeAidatId, new { @class = "form-control" })
        <div class="col-md-12">
            @Html.Label("Net Ödeme Ücreti (TL)")
            @Html.TextBoxFor(model => model.OdemeNetTutarı, new { @class = "form-control", @readonly = "readonly"})
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarası, "Kart Numarası")
            @Html.TextBoxFor(model => model.OdemeKartNumarası, new { @class = "form-control", @onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "16"})
            @Html.ValidationMessageFor(model => model.OdemeKartNumarası, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKrediKartıUzerindekiIsim, "Kart Üzerindeki İsim")
            @Html.TextBoxFor(model => model.OdemeKrediKartıUzerindekiIsim, new { @class = "form-control", @onkeypress="return /[A-Za-z]/i.test(event.key)" })
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıUzerindekiIsim, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımAy, "Kart Son Kullanım Tarihi - Ay")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımAy, new { @class = "form-control",@onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "2"})
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımAy, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımYıl, "Kart Son Kullanım Tarihi - Yıl")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımYıl, new { @class = "form-control",@onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "4"})
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımYıl, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-12">
            @Html.LabelFor(model => model.OdemeKrediKartıCVV, "CVV")
            @Html.TextBoxFor(model => model.OdemeKrediKartıCVV, new { @class = "form-control", @onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "3"})
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıCVV, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <button class="btn btn-outline-primary" style="margin-left:0.75cm" onclick="return confirm('Ödeme gerçekleştiriliyor, onaylıyor musunu?')">
        Ödeme Yap
        <i class="icon-payment ml-2"></i>
    </button>
}

FaturaYönetimSistemi/Views/Odeme/FaturaOdeme.cshtml
@using OdemeSistemi.Entities
@model Odeme

@{
    ViewData["Title"] = "FaturaOdeme";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!-- Top header -->
<header class="navbar-toggler p-4">
    <p class="w3-left text-dark font-weight-bolder" style="font-size:20px">Fatura Ödeme Sayfası</p>
    <p class="w3-right text-dark font-weight-normal" style="font-size:20px">
        <i class="icon-calendar mr-2"></i>@DateTime.Now.ToLongDateString()
    </p>
</header>
<hr />

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("FaturaOdeme", "Odeme", FormMethod.Post))
{
    <div class="d-flex flex-row col-md-12">
        @Html.HiddenFor(model => model.OdemeFaturaId, new { @class = "form-control" })
        <div class="col-md-12">
            @Html.Label("Net Ödeme Ücreti (TL)")
            @Html.TextBoxFor(model => model.OdemeNetTutarı, new { @class = "form-control", @readonly = "readonly"})
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-12">
            @Html.Label("Ödenecek Fatura Tipi")
            @Html.TextBoxFor(model => model.OdemeFaturaTipi, new { @class = "form-control", @readonly = "readonly"})
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarası, "Kart Numarası")
            @Html.TextBoxFor(model => model.OdemeKartNumarası, new { @class = "form-control", @onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "16"})
            @Html.ValidationMessageFor(model => model.OdemeKartNumarası, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKrediKartıUzerindekiIsim, "Kart Üzerindeki İsim")
            @Html.TextBoxFor(model => model.OdemeKrediKartıUzerindekiIsim, new { @class = "form-control", @onkeypress="return /[A-Za-z]/i.test(event.key)" })
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıUzerindekiIsim, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımAy, "Kart Son Kullanım Tarihi - Ay")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımAy, new { @class = "form-control", @onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "2" })
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımAy, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6">
            @Html.LabelFor(model => model.OdemeKartNumarasıSonKullanımYıl, "Kart Son Kullanım Tarihi- Yıl")
            @Html.TextBoxFor(model => model.OdemeKartNumarasıSonKullanımYıl, new { @class = "form-control",@onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "4" })
            @Html.ValidationMessageFor(model => model.OdemeKartNumarasıSonKullanımYıl, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="d-flex flex-row col-md-12">
        <div class="col-md-12">
            @Html.LabelFor(model => model.OdemeKrediKartıCVV, "CVV")
            @Html.TextBoxFor(model => model.OdemeKrediKartıCVV, new { @class = "form-control", @onkeypress="return /[0-9]/i.test(event.key)", @maxlength = "3" })
            @Html.ValidationMessageFor(model => model.OdemeKrediKartıCVV, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <button class="btn btn-outline-primary" style="margin-left:0.75cm" onclick="return confirm('Ödeme gerçekleştiriliyor, onaylıyor musunu?')">
        Ödeme Yap
        <i class="icon-payment ml-2"></i>
    </button>
}

FaturaYönetimSistemi/Views/Odeme/GetOdenmemisAidat.cshtml
@using EntityLayer.Concrete
@model List<Aidat>
@{
    ViewData["Title"] = "GetOdenmemisAidat";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!-- Top header -->
<header class="navbar-toggler p-4">
    <p class="w3-left text-dark font-weight-bolder" style="font-size:20px">Ödenmemiş Aidatlar</p>
    <p class="w3-right text-dark font-weight-normal" style="font-size:20px">
        <i class="icon-calendar mr-2"></i>@DateTime.Now.ToLongDateString()
    </p>
</header>
<hr />

@if (Model.Count != 0)
{
    <div class="w3-container pl-3 pt-3 mt-3 mb-3 bg-danger text-white" id="!aidatSayısı">
        <p>@ViewBag.odenmemisAidatSayısı adet ödenmemiş aidatınız bulunmaktadır.</p>
    </div>
}
else
{
    <div class="w3-container pl-3 pt-3 mt-3 mb-3 bg-success text-white" id="!aidatSayısı">
        <p>Ödenmemiş aidatınız bulunmamaktadır.</p>
    </div>
}

<table class="table table-bordered table-striped p-5">
    <thead>
        <tr>
            <th>Aidat No</th>
            <th>Aidat Tarihi</th>
            <th>Aidat Son Ödeme Tarihi</th>
            <th>Aidat Ücreti</th>
            <th>Aidat Sahibi</th>
            <th>Aidat Durumu</th>
        </tr>
    </thead>
    <tbody id="aidatTable">
        @foreach (var item in Model)
        {

            <tr>
                <td>@item.AidatId</td>
                <td>@(((DateTime)item.AidatTarihi).ToString("dd-MMM-yyyy"))</td>
                <td>@(((DateTime)item.AidatSonOdemeTarihi).ToString("dd-MMM-yyyy"))</td>
                <td>@item.AidatUcreti TL</td>
                <td>@item.AidatKullanıcı.KullanıcıIsım @item.AidatKullanıcı.KullanıcıSoyisim</td>
                <td>
                    <p class="text-danger">Ödenmedi<i class="icon-times ml-2 mr-4"></i><a class="btn btn-outline-success" href="/Odeme/AidatOdeme/@item.AidatId">Ödeme Yap<i class="icon-payment ml-2"></i></a></p>   
                </td>
            </tr>

        }
    </tbody>
</table>

FaturaYönetimSistemi/Views/Odeme/GetOdenmemisFatura.cshtml
@using EntityLayer.Concrete
@model List<Fatura>

@{
    ViewData["Title"] = "GetOdenmemisFatura";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!-- Top header -->
<header class="navbar-toggler p-4">
    <p class="w3-left text-dark font-weight-bolder" style="font-size:20px">Ödenmemiş Faturalarım</p>
    <p class="w3-right text-dark font-weight-normal" style="font-size:20px">
        <i class="icon-calendar mr-2"></i>@DateTime.Now.ToLongDateString()
    </p>
</header>
<hr />

@if (Model.Count != 0)
{
    <div class="w3-container pl-3 pt-3 mt-3 mb-3 bg-danger text-white" id="!faturaSayısı">
        <p>@ViewBag.odenmemisFaturaSayısı adet ödenmemiş faturanız bulunmaktadır.</p>
    </div>
}
else
{
    <div class="w3-container pl-3 pt-3 mt-3 mb-3 bg-success text-white" id="!aidatSayısı">
        <p>Ödenmemiş faturanız bulunmamaktadır.</p>
    </div>
}

<table class="table table-bordered table-striped p-5">
    <thead>
        <tr>
            <th>Fatura No</th>
            <th>Fatura Tarihi</th>
            <th>Fatura Son Ödeme Tarihi</th>
            <th>Fatura Ücreti</th>
            <th>Fatura Sahibi</th>
            <th>Fatura Tipi</th>
            <th>Fatura Durumu</th>
        </tr>
    </thead>
    <tbody id="faturaTable">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FaturaId</td>
                <td>@(((DateTime)item.FaturaTarihi).ToString("dd-MMM-yyyy"))</td>
                <td>@(((DateTime)item.FaturaSonOdemeTarihi).ToString("dd-MMM-yyyy"))</td>
                <td>@item.FaturaTutarı TL</td>
                <td>@item.FaturaKullanıcı.KullanıcıIsım @item.FaturaKullanıcı.KullanıcıSoyisim</td>
                <td>@item.FaturaTipi</td>
                <td>
                    @if (@item.FaturaOdendiMi)
                    {
                        <p class="text-success">Ödendi<i class="icon-check ml-2"></i></p>
                    }
                    else
                    {
                        <p class="text-danger">Ödenmedi<i class="icon-times ml-2 mr-4"></i><a class="btn btn-outline-success" href="/Odeme/FaturaOdeme/@item.FaturaId">Ödeme Yap<i class="icon-payment ml-2"></i></a></p>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>