FaturaYönetimSistemi/Controllers/AidatController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYönetimSistemi.Controllers
{
    public class AidatController : Controller
    {
        AidatManager aidatManager = new(new EFAidatRepository());
        KullanıcıManager kullanıcıManager = new(new EFKullanıcıRepository());
        public IActionResult GetAidat()
        {
            var kullanıcı = kullanıcıManager.GetKullanıcıBySession(User.Identity.Name);
            var aidatlar = aidatManager.GetAllQueryWithKullanıcı()
                .Where(x => x.AidatKullanıcıId == kullanıcı.KullanıcıId).ToList<Aidat>();
            ViewBag.odenmemisAidatSayısı = aidatManager.GetAllOdenmemisAidatSayısı(kullanıcı);
            ViewBag.toplamAidatSayısı = aidatManager.GetAllQuery().Where(x => x.AidatKullanıcıId == kullanıcı.KullanıcıId).Count();
            return View(aidatlar); 
        }
    }
}

FaturaYönetimSistemi/Controllers/DaireController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace FaturaYönetimSistemi.Controllers
{
    public class DaireController : Controller
    {
        DaireManager manager = new DaireManager(new EFDaireRepository());
        KullanıcıManager kullanıcıManager = new KullanıcıManager(new EFKullanıcıRepository());
        public IActionResult GetAllDaires()
        {
            return View(manager.GetAllDaireWithKullanıcı());
        }
        [HttpGet]
        public IActionResult AddDaire()
        {
            List<SelectListItem> kullanıcılar = kullanıcıManager.GetAllQuery().
                                                Select(x => new SelectListItem
                                                {
                                                    Text = x.KullanıcıIsım + " " + x.KullanıcıSoyisim,
                                                    Value = x.KullanıcıId.ToString()
                                                }).ToList();
            ViewBag.kullanıcılar = kullanıcılar;
            return View();
        }
        [HttpPost]
        public IActionResult AddDaire(Daire daire)
        {
            List<SelectListItem> kullanıcılar = kullanıcıManager.GetAllQuery().
                                                Select(x => new SelectListItem
                                                {
                                                    Text = x.KullanıcıIsım + " " + x.KullanıcıSoyisim,
                                                    Value = x.KullanıcıId.ToString()
                                                }).ToList();
            ViewBag.kullanıcılar = kullanıcılar;
            DaireValidator validator = new DaireValidator();
            ValidationResult validationResult = validator.Validate(daire);
            if (validationResult.IsValid)
            {
                manager.AddT(daire);
                return RedirectToAction("GetAllDaires");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult DeleteDaire(int id)
        {
            var daire = manager.GetQueryById(id);
            manager.DeleteT(daire);
            return RedirectToAction("GetAllDaires");
        }

        [HttpGet]
        public IActionResult UpdateDaire(int id)
        {
            var daire = manager.GetQueryById(id);
            List<SelectListItem> kullanıcılar = kullanıcıManager.GetAllQuery().
                                                Select(x => new SelectListItem
                                                {
                                                    Text = x.KullanıcıIsım + " " + x.KullanıcıSoyisim,
                                                    Value = x.KullanıcıId.ToString()
                                                }).ToList();
            ViewBag.kullanıcılar = kullanıcılar;
            return View(daire);
        }
        [HttpPost]
        public IActionResult UpdateDaire(Daire daire)
        {
            List<SelectListItem> kullanıcılar = kullanıcıManager.GetAllQuery().
                                                Select(x => new SelectListItem
                                                {
                                                    Text = x.KullanıcıIsım + " " + x.KullanıcıSoyisim,
                                                    Value = x.KullanıcıId.ToString()
                                                }).ToList();
            ViewBag.kullanıcılar = kullanıcılar;
            DaireValidator validator = new DaireValidator();
            ValidationResult validationResult = validator.Validate(daire);
            if (validationResult.IsValid)
            {
                manager.UpdateT(daire);
                return RedirectToAction("GetAllDaires");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

FaturaYönetimSistemi/Controllers/FaturaController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYönetimSistemi.Controllers
{
    public class FaturaController : Controller
    {
        FaturaManager faturaManager = new FaturaManager(new EFFaturaRepository());
        KullanıcıManager kullanıcıManager = new KullanıcıManager(new EFKullanıcıRepository());
        public IActionResult GetFatura()
        {
            var kullanıcı = kullanıcıManager.GetKullanıcıBySession(User.Identity.Name);
            var faturalar = faturaManager.GetAllQueryWithKullanıcı()
                .Where(x => x.FaturaKullanıcıId == kullanıcı.KullanıcıId).ToList<Fatura>();
            ViewBag.odenmemisFaturaSayısı = faturaManager.GetAllOdenmemisFaturaSayısı(kullanıcı);
            ViewBag.toplamFaturaSayısı = faturaManager.GetAllQuery().Where(x => x.FaturaKullanıcıId == kullanıcı.KullanıcıId).Count();
            return View(faturalar);
        }
    }
}

FaturaYönetimSistemi/Controllers/KullanıcıController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;

namespace FaturaYönetimSistemi.Controllers
{
    public class KullanıcıController : Controller
    {
        KullanıcıManager manager = new KullanıcıManager(new EFKullanıcıRepository());

        public IActionResult GetAllKullanıcıs()
        {
            return View(manager.GetAllQuery());
        }

        [HttpGet]
        public IActionResult AddKullanıcı()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddKullanıcı(Kullanıcı kullanıcı)
        {
            KullanıcıValidator validator = new();
            ValidationResult validationResult = validator.Validate(kullanıcı);
            if (validationResult.IsValid)
            {
                kullanıcı.KullanıcıSifre = PasswordGenerator();
                manager.AddT(kullanıcı);
                return RedirectToAction("GetAllKullanıcıs");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public IActionResult DeleteKullanıcı(int id)
        {
            var kullanıcı = manager.GetQueryById(id);
            manager.DeleteT(kullanıcı);
            return RedirectToAction("GetAllKullanıcıs");
        }
        [HttpGet]
        public IActionResult UpdateKullanıcı(int id)
        {
            var kullanıcı = manager.GetQueryById(id);
            return View(kullanıcı);
        }
        [HttpPost]
        public IActionResult UpdateKullanıcı(Kullanıcı kullanıcı)
        {
            KullanıcıValidator validator = new KullanıcıValidator();
            ValidationResult validationResult = validator.Validate(kullanıcı);
            if (validationResult.IsValid)
            {
                manager.UpdateT(kullanıcı);
                return RedirectToAction("GetAllKullanıcıs");
            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public string PasswordGenerator()
        {
            return Guid.NewGuid().ToString("d").Substring(1, 8);
        }
    }
}

FaturaYönetimSistemi/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Fatura Yönetim Sistemi</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/carousel-11/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <style>
        .w3-sidebar a {
            font-family: "Roboto", sans-serif
        }

        body, h1, h2, h3, h4, h5, h6, .w3-wide {
            font-family: "Montserrat", sans-serif;
        }
    </style>
    <script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js"></script>
</head>
<body class="w3-content" style="max-width:1920px">

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top border-right " style="z-index:3;width:250px" id="mySidebar">
        <div class="w3-container w3-display-container w3-padding-16">
            <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
            <h3 class="w3-wide"><b>Fatura Yönetim Sistemi</b></h3>
        </div>
        <div class="w3-padding-64 w3-large " style="font-weight:bold">
            <a href="/Admin/Home/AnaSayfa" class="w3-bar-item w3-button">Ana Sayfa<i class="icon-home ml-2"></i></a>
            <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
                Kullanıcı İşlemleri <i class="fa fa-caret-down"></i><i class="icon-user ml-2"></i>
            </a>
            <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                @Html.ActionLink("Kullanıcıları Listele/Düzenle/Sil", "GetKullanıcı", "Kullanıcı", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
                @Html.ActionLink("Kullanıcı Ekle", "AddKullanıcı", "Kullanıcı", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
            </div>
            <a onclick="myAccFunc1()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn1">
                Daire İşlemleri <i class="fa fa-caret-down"></i><i class="icon-bank ml-2"></i>
            </a>
            <div id="demoAcc1" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                @Html.ActionLink("Daire Bilgilerini Listele/Düzenle/Sil", "GetDaire", "Daire", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
            </div>
            <a onclick="myAccFunc2()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn2">
                Fatura İşlemleri <i class="fa fa-caret-down"></i><i class="icon-file-text-o ml-2"></i>
            </a>
            <div id="demoAcc2" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                @Html.ActionLink("Fatura Atama", "AddFatura", "Fatura", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
                @Html.ActionLink("Fatura Listele", "GetFatura", "Fatura", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
            </div>
            <a onclick="myAccFunc3()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn3">
                Aidat İşlemleri <i class="fa fa-caret-down"></i><i class="icon-file-text-o ml-2"></i>
            </a>
            <div id="demoAcc3" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                @Html.ActionLink("Aidat Atama", "AddAidat", "Aidat", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
                @Html.ActionLink("Tüm Kullanıclara Aidat Atama", "AddAidatForAllUser", "Aidat", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
                @Html.ActionLink("Aidat Listele", "GetAidat", "Aidat", new { Area = "Admin" }, new { @class = "w3-bar-item w3-button" })
            </div>
            <a href="/Admin/Odeme/GetOdemeler" class="w3-bar-item w3-button">Gelen Ödemeler <i class="icon-money ml-2"></i></a>
            <a href="/Admin/Mesaj/GetKullanıcılar" class="w3-bar-item w3-button">Mesajlarım <i class="icon-message ml-2"></i></a>
        </div>
        <hr />
        <a href="/Admin/Home/About" class="w3-bar-item w3-button">Uygulama Hakkında <i class="icon-question ml-2"></i></a>
        <a href="/Admin/YoneticiGiris/CikisYap" class="w3-bar-item w3-button">Çıkış Yap <i class="icon-sign-out ml-2"></i></a>
    </nav>

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
        <div class="w3-bar-item w3-padding-24 w3-wide">Fatura Yönetim Sistemi</div>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

        <!-- Push down content on small screens -->
        <div class="w3-hide-large" style="margin-top:83px"></div>

        <div class="w3-container">
            @RenderBody()
        </div>
    </div>

    <!-- Newsletter Modal -->
    <div id="newsletter" class="w3-modal" style="display: none;">
        <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
            <div class="w3-container w3-white w3-center">
                <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
                <h2 class="w3-wide">NEWSLETTER</h2>
                <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
                <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
                <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
            </div>
        </div>
    </div>
    

    <script>
        // Accordion
        function myAccFunc() {
            var x = document.getElementById("demoAcc");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        function myAccFunc1() {
            var x = document.getElementById("demoAcc1");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        function myAccFunc2() {
            var x = document.getElementById("demoAcc2");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        function myAccFunc3() {
            var x = document.getElementById("demoAcc3");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        document.getElementById("myBtn").click();
        document.getElementById("myBtn1").click();
        document.getElementById("myBtn2").click();
        document.getElementById("myBtn3").click();

        // Open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
    </script>

</body>
</html>

FaturaYönetimSistemi/Views/Shared/_FirstPageLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/carousel-11/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <style>
        .w3-sidebar a {
            font-family: "Roboto", sans-serif
        }

        body, h1, h2, h3, h4, h5, h6, .w3-wide {
            font-family: "Montserrat", sans-serif;
        }
    </style>
    <script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js"></script>
</head>
<body>
    <!-- Top header -->
    <header class="navbar-toggler p-4">
        <p class="w3-left">Fatura Yönetim Sistemi</p>
        <p class="w3-right">
            <i class="icon-calendar w3-margin-right"></i>@DateTime.Now.ToLongDateString()
        </p>
    </header>
    <hr />
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

FaturaYönetimSistemi/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <title>Fatura Yönetim Sistemi</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/carousel-11/fonts/icomoon/style.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <style>
        .w3-sidebar a {
            font-family: "Roboto", sans-serif
        }

        body, h1, h2, h3, h4, h5, h6, .w3-wide {
            font-family: "Montserrat", sans-serif;
        }
    </style>
    <script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js"></script>
</head>
<body class="w3-content" style="max-width:1920px">

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top border-right " style="z-index:3;width:250px" id="mySidebar">
        <div class="w3-container w3-display-container w3-padding-16">
            <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
            <h3 class="w3-wide"><b>Fatura Yönetim Sistemi</b></h3>
        </div>
        <div class="w3-padding-64 w3-large text-center" style="font-weight:bold">
            <a href="/Home/AnaSayfa" class="w3-bar-item w3-button">Ana Sayfa<i class="icon-home ml-2"></i></a>
            <a href="/Fatura/GetFatura" class="w3-bar-item w3-button">Faturalarım<i class="icon-file-text-o ml-2"></i></a>
            <a href="/Aidat/GetAidat" class="w3-bar-item w3-button">Aidatlarım<i class="icon-file-text-o ml-2"></i></a>
            <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
                Mesajlar <i class="fa fa-caret-down"></i><i class="icon-message ml-2"></i>
            </a>
            <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                <a href="/Mesaj/AddMesaj" class="w3-bar-item w3-button">Mesaj Gönder</a>
                <a href="/Mesaj/GetYoneticiList" class="w3-bar-item w3-button">Gönderilen Mesajlar</a>
            </div>
            <a onclick="myAccFunc1()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn1">
                Ödeme Yap <i class="fa fa-caret-down"></i><i class="icon-message ml-2"></i>
            </a>
            <div id="demoAcc1" class="w3-bar-block w3-hide w3-padding-large w3-medium w3-show">
                <a href="/Odeme/GetOdenmemisAidat" class="w3-bar-item w3-button">Aidat Öde</a>
                <a href="/Odeme/GetOdenmemisFatura" class="w3-bar-item w3-button">Fatura Öde</a>
            </div>
        </div>
        <hr />
        <a href="/Home/Contact" class="w3-bar-item w3-button w3-padding">İletişim<i class="icon-contact_mail ml-2"></i></a>
        <a href="/Home/About" class="w3-bar-item w3-button w3-padding">Uygulama Hakkında<i class="icon-question ml-2"></i></a>
        <a href="/KullanıcıGiris/CikisYap" class="w3-bar-item w3-button w3-padding">Çıkış Yap<i class="icon-sign-out ml-2"></i></a>
    </nav>

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
        <div class="w3-bar-item w3-padding-24 w3-wide">Fatura Yönetim Sistemi</div>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

        <!-- Push down content on small screens -->
        <div class="w3-hide-large" style="margin-top:83px"></div>


        <div class="w3-container">
            @RenderBody()
        </div>
        <!-- End page content -->
    </div>

    <!-- Newsletter Modal -->
    <div id="newsletter" class="w3-modal" style="display: none;">
        <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
            <div class="w3-container w3-white w3-center">
                <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
                <h2 class="w3-wide">NEWSLETTER</h2>
                <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
                <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
                <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
            </div>
        </div>
    </div>

    <script>
        // Accordion
        function myAccFunc() {
            var x = document.getElementById("demoAcc");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }

        function myAccFunc1() {
            var x = document.getElementById("demoAcc1");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }


        document.getElementById("myBtn").click();
        document.getElementById("myBtn1").click();


        // Open and close sidebar
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("myOverlay").style.display = "block";
        }

        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("myOverlay").style.display = "none";
        }
    </script>


</body>
</html>